### ISSUE TITLE
Windows compatibility

### ISSUE THREAD

**Issue by mandrolic** [ahultgren/swagger-elm#1]
The swagger to json script is bash only - not sure how this will cope on windows.
Most of the rest is ok I think this is the only architecture sensitive thing

**Comment by ahultgren** [comment]
I would need help from someone using windows for this. I think something like `type swagger.json > swagger-to-elm > elm-format` should work if I convert `swagger-to-elm` to a node-script (using `elm-stdio` programatically) and let usage of `elm-format` be up to the user.

**Comment by ahultgren** [comment]
So I finally got around to fixing this. If you (or anyone else who happens to read this and uses windows) feel like testing if it works I would very much appreciate it.

**Comment by gantony** [comment]
First, thank you for creating this package!!

I tested it on Windows 7, and it works :)
Both `type swagger.json | swagger-to-elm | elm-format --stdin` and `type swagger.json | swagger-to-elm` work as expected.

**Comment by gantony** [comment]
Messing around a bit more with this, if we want to seamlessly make it work on Windows (i.e. get `npm run test-build` to work as is), we can create a `cat.bat` file with the following content:    

    @echo off
    call type %1

**Comment by ahultgren** [comment]
Great! Since it works I'm closing this issue. I don't know enough about windows development to tell if a bat file is the way to go, but if you submit a PR I'll consider it there.
