### ISSUE TITLE
Map / dict support

### ISSUE THREAD

**Issue by mxinden** [ahultgren/swagger-elm#10]
Are there any steps planned on supporting [`map` / `dict`](http://swagger.io/specification/#model-with-map-dictionary-properties-88) in the near future? 

We are currently looking into GRPC and its integration with Elm for [Prometheus Alertmanager](https://github.com/prometheus/alertmanager). `Map` / `dict` support would be a crucial feature for us. (See [PR](https://github.com/prometheus/alertmanager/pull/698))

**Comment by ahultgren** [comment]
I'm afraid there's plenty of plans but very little time :) I might find some time over easter, but I'd gladly accept a PR.
