### ISSUE TITLE
Support for specifying module name for output

### ISSUE THREAD

**Issue by abingham** [ahultgren/swagger-elm#16]
Is there a way to specify the name of the module generated by swagger-to-elm? I can't find one.

This feature would be useful in cases where swagger-to-elm is used as part of an automated build process and I need the output as part of a larger Elm project.

**Comment by ahultgren** [comment]
I agree that would be a useful feature! It's not possible yet though. Meanwhile you could do something like `cat swagger.json | swagger-to-elm | sed 's/^module Decoder/module Mymodule/' > Mymodule.elm`.

**Comment by abingham** [comment]
Ok, thanks.
