### ISSUE TITLE
The code on the web page is missing some indentation

### ISSUE THREAD

**Issue by mattiasw2** [ahultgren/swagger-elm#25]
Took me many hours to find your already working solution for converting swagger-json to elm. Thank you!

Code looks fine, and I didn't even have to install, just used your webpage.

However, I needed to make a few regex replacements to make it work, the body of the decoders start in column 0 on the web page. I had to replace "^list " by " list ",  and "^decode " by " decode ".

**Comment by ahultgren** [comment]
Hm. The output is meant to be run through elm-format. Did you do that?

As an aside, i don't have time to maintain this anymore and plan to abandon it in favor of swagger-codegen.

**Comment by mattiasw2** [comment]
No, I didn't run the webpage result through elm-format, didn't realize that was necessary. Yes, I agree, fixing swagger-codegen for Elm would be nice. However, I failed to run my swagger.json through v2.4, I do not know what failed.
