### ISSUE TITLE
Handle sanitizing of types/field

### ISSUE THREAD

**Issue by mandrolic** [ahultgren/swagger-elm#3]
for e.g UpperCamelCase JSON properties will currently generate illegal Elm

**Comment by ahultgren** [comment]
As of latest commit:
- [x] handle upper case fields
- [x] handle lower case definitions
- [x] handle illegal characters (anything but /^[a-zA-Z][a-zA-Z'_]*$) (TODO: find official list)
- [x] handle reserved keywords (e.g. port, type, import? exposing? Need official list)

**Comment by ahultgren** [comment]
Done!
