### ISSUE TITLE
Error: missing path in request

### ISSUE THREAD

**Issue by Frituurpanda** [ahultgren/swagger-elm#4]
After default installation on macOS and trying "cat swagger.json | swagger-to-elm | elm-format --stdin" I got the following error: {"error":"Missing { path } in request"}%. Can't really find where the problem lies after debugging a bit. Could you maybe help shine some light on how to get the project to work?

**Comment by ahultgren** [comment]
It sounds like the problem is in the swagger file. Do you have a minimal working example of the swagger to reproduce the error?

**Comment by Frituurpanda** [comment]
I've tried it on the swagger [file](https://github.com/ahultgren/swagger-elm/blob/master/tests/fixtures/swagger.json) in the swagger-elm project and on some other files, all with the same result. Can you maybe try it on the default [swagger](https://github.com/ahultgren/swagger-elm/blob/master/tests/fixtures/swagger.json) in the project?

**Comment by ahultgren** [comment]
Hm, I just tried and it worked... I also tried a fresh install and it worked too. Are you using the latest version of node?

**Comment by Frituurpanda** [comment]
Interesting, maybe that's the issue. I'm running "node --version v7.5.0" You?

**Comment by ahultgren** [comment]
Same. This is weird. Do you get the same error running just `cat swagger.json | swagger-to-elm`?

**Comment by Frituurpanda** [comment]
Yeah. Just ran it on two machines and got the same result: "cat swagger.json | swagger-to-elm
{"error":"Missing { path } in request"}%" I'm think i'm missing something, not sure what yet..

**Comment by Frituurpanda** [comment]
This issue was solved by uninstalling the default elm-stdio and installing the authors elm-stdio (ahultgren/node-elm-stdio) instead.
