### ISSUE TITLE
Nested records - naming issue? 

### ISSUE THREAD

**Issue by nqthqn** [ahultgren/swagger-elm#9]
Here is a copy of my swagger.json and Decoder.elm:

https://gist.github.com/nqthqn/223ce10dab2fd5b3713623e36f69852d

After running the generator I run into this compilation error:

```
-- NAMING ERROR ------------------------------------------------ ././Decoder.elm

Cannot find type `IdlUsersRequestIds`

185|     { ids : Maybe (List IdlUsersRequestIds)
                             ^^^^^^^^^^^^^^^^^^


Detected errors in 1 module.
```

I've started trying to map the names that need to change.

```
IdlUserRecordRoles           ->  IdlRole
IdlUsersUsers                ->  IdlUser
IdlUsersRecordRecords        ->  IdlUserRecord
IdlUsersRequestIds           ->  ?
IdlGameplaysGameplays        ->  IdlGameplay
IdlUserRoles                 ->  IdlRole
IdlGimagesGimages            ->  IdlGimage
IdlGameplaysReferralGameIds  ->  ?
IdlGameplaysGameplays        ->  IdlGameplay
```

Any ideas why this might be happening?

**Comment by ahultgren** [comment]
This is weird, `IdlUsersRequestIds` should indeed be `String` (formats are not supported yet). I'll look into it tonight or in the weekend.

If you have the time and ability, would you like to add a minimal failing example to `https://github.com/ahultgren/swagger-elm/blob/master/tests/fixtures/swagger.json` (that would cause the same error when the tests are run)? That would help a lot to make me look into this sooner :)

**Comment by nqthqn** [comment]
Oh you know what? I just realized it should be a `String`! Our Ids are strings, oddly enough. My "find and replace" method is flawed.

And YES, I will get you a MFE pronto 👍

**Comment by ahultgren** [comment]
AFAICT this is solved 🎉
